added jq

diff --git a/launchpad b/launchpad
--- a/launchpad
+++ b/launchpad
@@ -4,7 +4,7 @@
 # ERROR: Let the user know if the script fails
 ###############################################################################
 
-trap 'ret=$?; test $ret -ne 0 && printf "\n   \e[31m\033[0m  Formation failed  \e[31m\033[0m\n" >&2; exit $ret' EXIT
+trap 'ret=$?; test $ret -ne 0 && printf "\n   \e[31m?\033[0m  Formation failed  \e[31m?\033[0m\n" >&2; exit $ret' EXIT
 
 set -e
 
@@ -16,7 +16,7 @@ if [ -e utils ]; then
 	cd "$(dirname "${BASH_SOURCE[0]}")" \
 		&& . "utils"
 else
-	printf "\n ⚠️  ./utils not found  💃🏾 First, you need to utils on your haters\n"
+	printf "\n ??  ./utils not found  ???? First, you need to utils on your haters\n"
 	exit 1
 fi
 
@@ -42,11 +42,11 @@ MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK, .lKWMM
 d,     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,   .lKW
 MXx,   ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     .l
-MMMXx, ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,       
-MMMMMXxdO00000000000KNMMMMMMMMMMMWX00000000000k'       
-MMMMMMMNO:..........,OMMMMMMMMMMMX:...........         
-MMMMMMMMMXx,        .kMMMMMMMMMMMK,                    
-MMMMMMMMMMMXx,      .kMMMMMMMMMMMK,                    
+MMMXx, ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,
+MMMMMXxdO00000000000KNMMMMMMMMMMMWX00000000000k'
+MMMMMMMNO:..........,OMMMMMMMMMMMX:...........
+MMMMMMMMMXx,        .kMMMMMMMMMMMK,
+MMMMMMMMMMMXx,      .kMMMMMMMMMMMK,
 MMMMMMMMMMMMMXx,    .kMMMMMMMMMMMK,        ............
 MMMMMMMMMMMMMMMXx,  .kMMMMMMMMMMMK,       :0KK000KKKKKK
 MMMMMMMMMMMMMMMMMXx''OMMMMMMMMMMMK,       oWMMMMMMMMMMM
@@ -57,38 +57,38 @@ MMMMMMMMMMMMMMMMMMMMMMMMMXdc'             oWMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMWK:            oWMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
-╭───────────────────────────────────────────────────╮
-│  Okay developers now let's get ready to ${bold}launch${normal}.   │
-│───────────────────────────────────────────────────│
-│  Safe to run multiple times on the same machine.  │
-│  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based   │
-│  on what is already installed on the machine.     │
-╰───────────────────────────────────────────────────╯
+?????????????????????????????????????????????????????
+?  Okay developers now let's get ready to ${bold}launch${normal}.   ?
+?????????????????????????????????????????????????????
+?  Safe to run multiple times on the same machine.  ?
+?  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based   ?
+?  on what is already installed on the machine.     ?
+?????????????????????????????????????????????????????
    ${dim}$(get_os) $(get_os_version) ${normal} // ${dim}$BASH ${normal} // ${dim}$BASH_VERSION${reset}
 "
 
 ###############################################################################
 # CHECK: Internet
 ###############################################################################
-chapter "Checking internet connection…"
+chapter "Checking internet connection?"
 check_internet_connection
 
 ###############################################################################
 # PROMPT: Password
 ###############################################################################
-chapter "Caching password…"
+chapter "Caching password?"
 ask_for_sudo
 
 ###############################################################################
 # PROMPT: SSH Key
 ###############################################################################
-chapter 'Checking for SSH key…'
+chapter 'Checking for SSH key?'
 ssh_key_setup
 
 ###############################################################################
 # INSTALL: Dependencies
 ###############################################################################
-chapter "Installing Dependencies…"
+chapter "Installing Dependencies?"
 
 # -----------------------------------------------------------------------------
 # XCode
@@ -97,7 +97,7 @@ if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
 	test -d "${xpath}" && test -x "${xpath}" ; then
 	print_success_muted "Xcode already installed. Skipping."
 else
-	step "Installing Xcode…"
+	step "Installing Xcode?"
 	xcode-select --install
 	print_success "Xcode installed!"
 fi
@@ -111,16 +111,16 @@ fi
 # NVM
 # -----------------------------------------------------------------------------
 if ! [ -e $NVM_DIR ]; then
-	step "Installing NVM…"
-	# ensures that nvm 
+	step "Installing NVM?"
+	# ensures that nvm
 	touch ~/.bash_profile
 	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
 	# This loads nvm for the terminal session
 	export NVM_DIR="$HOME/.nvm"
-	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
-	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
+	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
 	print_success "NVM installed!"
-	step "Installing latest Node…"
+	step "Installing latest Node?"
 	nvm install 10
 	nvm use 10
 	nvm run node --version
@@ -133,7 +133,7 @@ fi
 # Homebrew
 # -----------------------------------------------------------------------------
 if ! [ -x "$(command -v brew)" ]; then
-	step "Installing Homebrew…"
+	step "Installing Homebrew?"
 	curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
 	export PATH="/usr/local/bin:$PATH"
 	print_success "Homebrew installed!"
@@ -142,7 +142,7 @@ else
 fi
 
 if brew list | grep -Fq brew-cask; then
-	step "Uninstalling old Homebrew-Cask…"
+	step "Uninstalling old Homebrew-Cask?"
 	brew uninstall --force brew-cask
 	print_success "Homebrew-Cask uninstalled!"
 fi
@@ -151,7 +151,7 @@ fi
 # INSTALL: brews
 ###############################################################################
 if [ -e $cwd/sources/brews ]; then
-	chapter "Installing Homebrew formulae…"
+	chapter "Installing Homebrew formulae?"
 
 	for brew in $(<$cwd/sources/brews); do
 		install_brews $brew
@@ -161,14 +161,14 @@ fi
 ###############################################################################
 # UPDATE: Homebrew
 ###############################################################################
-chapter "Updating Homebrew formulae…"
+chapter "Updating Homebrew formulae?"
 brew update
 
 ###############################################################################
 # INSTALL: casks
 ###############################################################################
 if [ -e $cwd/sources/casks ]; then
-	chapter "Installing apps via Homebrew…"
+	chapter "Installing apps via Homebrew?"
 
 	for cask in $(<$cwd/sources/casks); do
 	    install_application_via_brew $cask
@@ -178,7 +178,7 @@ fi
 ###############################################################################
 # INSTALL: Mac App Store Apps
 ###############################################################################
-chapter "Installing apps from App Store…"
+chapter "Installing apps from App Store?"
 if [ -x mas ]; then
 
 	print_warning "Please install mas-cli first: brew mas. Skipping."
@@ -204,14 +204,14 @@ fi
 ###############################################################################
 # CLEAN: Homebrew files
 ###############################################################################
-chapter "Cleaning up Homebrew files…"
+chapter "Cleaning up Homebrew files?"
 brew cleanup 2> /dev/null
 
 ###############################################################################
 # INSTALL: npm packages
 ###############################################################################
 if [ -e $cwd/sources/npm ]; then
-	chapter "Installing npm packages…"
+	chapter "Installing npm packages?"
 
 	for pkg in $(<$cwd/sources/npm); do
 		KEY="${pkg%%::*}"
@@ -222,6 +222,6 @@ fi
 
 
 ###############################################################################
-# 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀#
+# ??????????????????????????????????????????????????????????????????????#
 ###############################################################################
 we_have_lift_off
